# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Navigation_2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Navigation_2

pod 'SnapKit'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'RealmSwift', '~> 10.31'

end

target 'Navigation_2_release' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Navigation_2_release

pod 'SnapKit'
pod 'Firebase/Core'
pod 'Firebase/Auth'
end

target 'StorageService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit'
pod 'Firebase/Core'
pod 'Firebase/Auth'

  # Pods for StorageService

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['VALID_ARCHS'] = 'arm64, arm64e, x86_64'
  end
end

